using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ABriefHistory.CSharp2
{
    // Iterators allow a method to produce a sequence lazily using 'yield return'.
    // The compiler turns the method into a state machine that remembers its position
    // between iterations, without building the whole collection up front
    internal class Iterators
    {
        // They let you generate sequences lazily
        // They avoid building temporary lists
        // They enable writing cleaner enumeration logic
        public static void Run()
        {
            foreach (int n in GetNumbers())
            {
                Console.WriteLine(n);
            }

            foreach(int n in Range(5, 4))
            {
                Console.WriteLine(n);
            }
        }

        // The moethod becomes a state machine generated by the compile
        static IEnumerable<int> GetNumbers()
        {
            yield return 1;
            yield return 2;
            yield return 3;
            // Does not return all values at once. It means:
            // 1) give the caller 1
            // 2) pause the method
            // 3) resume later
            // 4) give 2
            // 5) pause again
            // 6) resume later
            // 7) give 3
        }

        // Without iterators, you'd usually write
        // Builds the whole collection first
        // Uses extra memory
        // Is less elegant for sequences
        static IEnumerable<int> GetNumbersOld()
        {
            List<int> numbers = new List<int>();
            numbers.Add(1);
            numbers.Add(2);
            numbers.Add(3);
            return numbers;
        }

        static IEnumerable<int> Range(int start, int count)
        {
            for (int i = start; i < start + count; i++)
            {
                // You can also stop early
                if(i > 10)
                {
                    yield break;
                }
                yield return i;
            }
        }
    }
}
