using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ABriefHistory.CSharp3
{
    // Partial methods let an autogenerated partial class provide customizable hooks for manual authoring that "melt away" if unused
    // "Melt away" if unsed: no implementation => no method => no call => zero runtime cost
    // With normal methods you always have: method exists, call exists, overhead exists
    // With partial methods: optional hook with zero cost if unused
    internal class PartialMethods
    {
        // A partial method is a method that":
        // 1) Can be declared in one part of a partial class
        // 2) Can be optionally implemented in another part
        // 3) If you don't implement it - it disappears completly
        public static void Run()
        {
            var p = new PersonPart();
            p.DoWork();
        }
    }

    // Part 1 (e.g. autogenerated code)
    public partial class PersonPart
    {
        public void DoWork()
        {
            Console.WriteLine("Doing work...");
            OnWorkStarted(); // hook
        }

        partial void OnWorkStarted();
    }

    // Part 2 (manual code - optional)
    public partial class PersonPart
    {
        // Partial methods:
        // 1) Must be partial
        // 2) Must return void
        // 3) Cannot have access modifiers (implicitly private)
        // 4) Cannot have 'out' parameters
        // 5) Can be omitted (and then removed by compiler)
        partial void OnWorkStarted()
        {
            Console.WriteLine("Hook: Work started!");
        }
    }

    // It's useful in generated code
    // Example: Tool generates class => you extend behavior without modifying generated code

    // generated
    public partial class ExampleGenerated
    {
        public void Save()
        {
            OnSaving();
            Console.WriteLine("Saving...");
        }

        partial void OnSaving(); // declaration (required)
    }

    public partial class ExampleGenerated
    {
        partial void OnSaving() {
            Console.WriteLine("Validating before save...");
        }
    }
}

